[build]
  functions = "functions"
  publish = "."

# Headers for better SEO and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    # Removed X-Frame-Options to allow iframe embedding
    # X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    # Allow iframe embedding from any domain
    Content-Security-Policy = "frame-ancestors *"

# Proper content types for SEO files
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"

[[headers]]
  for = "/feed.json"
  [headers.values]
    Content-Type = "application/feed+json; charset=UTF-8"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 

# Umleitungen für blutdruck-test.html
[[redirects]]
  from = "/blutdruck-test"
  to = "/blutdruck-test-merged.html"
  status = 301
  force = true

[[redirects]]
  from = "/blutdruck-test/"
  to = "/blutdruck-test-merged.html"
  status = 301
  force = true

# Alte Blutdruck-Analyse-Seite umleiten
[[redirects]]
  from = "/blutdruck-analyse"
  to = "/blutdruck-test-merged.html"
  status = 301
  force = true

[[redirects]]
  from = "/blutdruck-analyse/"
  to = "/blutdruck-test-merged.html"
  status = 301
  force = true 