[build]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 

# Umleitungen für blutdruck-test.html
[[redirects]]
  from = "/blutdruck-test"
  to = "/blutdruck-test-merged.html"
  status = 200

[[redirects]]
  from = "/blutdruck-test/"
  to = "/blutdruck-test-merged.html"
  status = 200 

# Alte Blutdruck-Analyse-Seite umleiten
[[redirects]]
  from = "/blutdruck-analyse"
  to = "/blutdruck-test-merged.html"
  status = 200

[[redirects]]
  from = "/blutdruck-analyse/"
  to = "/blutdruck-test-merged.html"
  status = 200 